pipeline {
    agent any

    environment {
        IMAGE_NAME = 'rembg-api'
        CONTAINER_NAME = 'rembg-container'
        PORT = '8000'
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/Anand19987i/bg-remove.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Stop & Remove Old Container') {
            steps {
                script {
                    sh "docker rm -f $CONTAINER_NAME || true"
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh "docker run -d -p $PORT:$PORT --name $CONTAINER_NAME $IMAGE_NAME"
            }
        }
    }

    post {
        success {
            echo "🚀 Deployment successful!"
        }
        failure {
            echo "❌ Deployment failed."
        }
    }
}
